trigger:
- main
- refs/tags/*

pool:
  vmImage: ubuntu-latest

steps:  
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish (win-x64)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--self-contained --arch x64 --os win'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish (linux-x64)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--self-contained --arch x64 --os linux'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish (linux-arm)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--self-contained --arch arm --os linux'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish (linux-arm64)'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--self-contained --arch arm64 --os linux'
    zipAfterPublish: false
    modifyOutputPath: false

- task: Bash@3
  displayName: 'mkdir publish'
  inputs:
    targetType: 'inline'
    script: 'mkdir publish'

- task: Bash@3
  displayName: 'copy binary (win-x64)'
  inputs:
    targetType: 'inline'
    script: 'cp src/bin/Release/net8.0/win-x64/publish/UT1Downloader.exe publish/UT1Downloader-win-x64.exe'

- task: Bash@3
  displayName: 'copy binary (linux-x64)'
  inputs:
    targetType: 'inline'
    script: 'cp src/bin/Release/net8.0/linux-x64/publish/UT1Downloader publish/UT1Downloader-linux-x64'

- task: Bash@3
  displayName: 'copy binary (linux-arm)'
  inputs:
    targetType: 'inline'
    script: 'cp src/bin/Release/net8.0/linux-arm/publish/UT1Downloader publish/UT1Downloader-linux-arm'

- task: Bash@3
  displayName: 'copy binary (linux-arm64)'
  inputs:
    targetType: 'inline'
    script: 'cp src/bin/Release/net8.0/linux-arm64/publish/UT1Downloader publish/UT1Downloader-linux-arm64'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'publish'
    ArtifactName: 'publish'
    publishLocation: 'Container'

- task: GitHubRelease@0
  displayName: Release to GitHub
  inputs:
    gitHubConnection: 'GitHub.com'
    repositoryName: frostieDE/ut1downloader
    assets: |
      'publish/**'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))